# See: https://docs.github.com/en/actions/writing-workflows
---
name: Update scoop bucket

on:
  release:
    types: [published]

jobs:
  update:
    name: Update
    runs-on: windows-latest
    steps:
      - name: Install scoop
        shell: pwsh
        run: irm get.scoop.sh | iex
      - name: Install hub
        run: scoop install hub
      - name: Checkout scoop bucket
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_SCOOP_BUCKET }}
          repository: imunproductive/asimov-scoop-bucket
      - name: Update
        shell: pwsh
        run: ./bin/auto-pr.ps1 -push
